#!/usr/bin/env python

import argparse
import binascii

root_parser = argparse.ArgumentParser()
root_parser.add_argument('hex_data')

args = root_parser.parse_args()

print(binascii.hexlify(binascii.unhexlify(args.hex_data)[::-1]))
